language: java
script: mvn clean verify
before_install:
  - chmod +x mvnw
services:
  - postgresql
os:
  - linux
addons:
  postgresql: '12'
  apt:
    packages:
      - postgresql-12
      - postgresql-client-12
env:
  global:
    - PGPORT=5432
    - DB_NAME=testsystem
    - DB_USER=postgres
    - DB_PASSWORD=super123
before_script:
  - psql --command="CREATE USER ${DB_USER};"
  - psql --command="CREATE DATABASE ${DB_NAME} WITH OWNER = ${DB_USER};"
  - psql --dbname=$DB_NAME --file=sql/create-tables.sql
