language: java
before_install:
  - chmod +x mvnw
services:
  - postgresql
os:
  - linux
addons:
  postgresql: '12'
  apt:
    packages:
      - postgresql-12
      - postgresql-client-12
env:
  global:
    - PGPORT=5432
before_script:
  - psql -c 'create database testsystem;' -U postgres
  - psql -c "CREATE USER postgres WITH PASSWORD 'super123';" -U postgres
script: mvn clean verify
