language: java
script: mvn clean verify
before_install:
  - chmod +x mvnw
services:
  - postgresql
before_script:
  - psql -c 'create database testsystem;' -U postgres
os:
  - linux
env:
  global:
    - PGUSER=postgres
    - PGPORT=5432