language: java
dist: xenial
os: linux
before_install:
  # Use trust instead of peer authentication:
  - >-
    sudo sed -i
    -e '/local.*peer/s/postgres/all/'
    -e 's/peer\|md5/trust/g'
    /etc/postgresql/13/main/pg_hba.conf
  # Restart the PostgreSQL service:
  - sudo service postgresql@13-main restart
  - chmod +x mvnw
services:
  - postgresql

addons:
  # Use a different PostgreSQL version than the default:
  postgresql: '13'
  apt:
    update: true
    packages:
      - postgresql-13
      - postgresql-13-postgis-3

env:
  global:
    - PGUSER=postgres
    - PGPASSWORD=super123
    - PGPORT=5432
before_script:
  - psql -c 'create database testsystem' -U postgres -p 5432
#  - psql -c "CREATE USER postgres WITH CREATEDB PASSWORD 'super123';" -U postgres -p 5433
script: mvn clean verify
